version: "3"

tasks:
  build:
    cmds:
      - go build cmd/cmdbook/cb.go
  install:
    cmds:
      - go install cmd/cmdbook/cb.go
  test:
    cmds:
      - go test -v ./...
  fmt:
    cmds:
      - gofmt -w -l .
  vet:
    cmds:
      - go vet ./...
  govulncheck:
    cmds:
      - govulncheck ./...
