version: "3"

tasks:
  build:
    cmds:
      - go build cb.go
  install:
    cmds:
      - go install cb.go
  fmt:
    cmds:
      - gofmt -w -l main.go
  goimports:
    cmds:
      - goimports -w -l main.go
  vet:
    cmds:
      - go vet .
  staticcheck:
    cmds:
      - staticcheck main.go
